#!/usr/bin/env ruby
#

begin
  # make sure it errors sanely on no input
  ipfile_name = ARGV[0] ? ARGV[0] : " "
  config_name = ARGV[1] ? ARGV[1] : " "

  # exit cleanly if the files are not valid
  unless File.exist?(ipfile_name) && File.exist?(config_name)
    STDERR.puts "usage: ipmap mapfile config"
    exit 1 
  end

  ipmap = Array.new
  ipfile = File.new(ipfile_name, 'r')
  while line = ipfile.gets
    ipmap.push line.split " "
  end
  new_filename = [Time.now.strftime("%H:%M:%S:%2N"), config_name].join "-"
  
  config_file = File.new(config_name, 'r')
  new_config_file = File.new(new_filename, 'w')
  
  # remap the file
  while line = config_file.gets
    ipmap.each do |x|
      if line.match x[0]
        line = line.gsub(x[0], x[1])
      end
    end
    new_config_file.puts line
  end
end
